### ISSUE TITLE
slope feature broken?

### ISSUE THREAD

**Issue by Lemente** [rlars/railbuilder#3]
After right clicking and dragging (to make the rails go up or down) the green circles don't appear anymore until I restart the game.
I can still click on them if I know where they are. I also managed to make some slope happen by clicking randomly

This happens with the Minetest Game, and the 0.8.1.1 release of railbuilder.

Amazing mod by the way!

**Comment by rlars** [comment]
Hi,
thanks for giving this mod a try!
I checked multiple times and only in one session I had some strange behaviour: circles appeared but I could not build when clicking (just the opposite of what you experienced 😀 )

Please also note that the circles shown currently depend on your position (!) and not on the view direction. Honestly, I should improve this, as it is really unexpected and annoying even to me.

**Comment by Lemente** [comment]
thanks for the answer!

Just tried again with Minetest 5.6, the Minetest Game, railbuilder and its dependencies.

When I leftclick to change the elevation, then the green circles stop showing until restart.

a series of screenshots to illustrate

looking at the rails, not clicking
![screenshot_20220904_234218](https://user-images.githubusercontent.com/27686967/188334660-ce49dd6e-27b5-4cdf-945c-1422ec1deea1.png)
left-clicking and going up one circle
![screenshot_20220904_234225](https://user-images.githubusercontent.com/27686967/188334661-183209ec-550c-49b1-a19d-05f5a1348ca6.png)
going up to the second circle
![screenshot_20220904_234230](https://user-images.githubusercontent.com/27686967/188334663-20da355e-a6cd-47a9-b0ce-071dc0c00cdb.png)
looking at the rails, not clicking
![screenshot_20220904_234241](https://user-images.githubusercontent.com/27686967/188334666-bff2c8a4-4f0b-4bcb-8eb2-7ef204b00992.png)

am I doing something wrong?

**Comment by rlars** [comment]
I finally found the issue (and more). I fixed it and will create a new version soon.
